### ISSUE TITLE
some change for network

### ISSUE THREAD

**Issue by sathouel** [fanfaresimulator/fanfaresimulator#20]
@FooB4r @emersion 
1 - please replace signal partitionChoiceRecv by pupitreChoiceRecv in server.hpp
2 - please replace method `void sendInstrumentChoice(Instrument instrument);` by 
`void sendPupitreChoice(Pupitre pupitre);` in client.hpp

**Comment by emersion** [comment]
Fixed in https://github.com/fanfaresimulator/fanfaresimulator/pull/22/commits/640fbc498f7e98e43875932ca5ac9efc0e4b006b
