### ISSUE TITLE
Note display and repartition

### ISSUE THREAD

**Issue by FooB4r** [fanfaresimulator/fanfaresimulator#30]
After a while on many partitions, these appear :

![bug](https://user-images.githubusercontent.com/18214834/33808677-e237e0f8-ddea-11e7-9c30-bcb375d860be.png)

![bug2](https://user-images.githubusercontent.com/18214834/33808680-ec8b44d2-ddea-11e7-9947-174042470d18.png)

Partition is only playable on one track. The track on which there are still notes changes it's key (the piano keyboard equivalent) so that the song can now be played, but only on one key.

**Comment by emersion** [comment]
Can you provide a sample MIDI file to reproduce the bug?

**Comment by FooB4r** [comment]
* 1st and 2nd tuba on default willi wonka theme
* 2nd guitar on [Californication](https://freemidi.org/download-16362-californication-3-red-hot-chili-peppers)
* track 2 and 3 eventally are the most compelling examples. Track 4 does some weird stuff at the end on [CliffsOfDover](https://freemidi.org/download-7704-cliffs-of-dover-eric-johnson)

**Comment by FooB4r** [comment]
Not really fixed
* 1st guitar on [Californication](https://freemidi.org/download-16362-californication-3-red-hot-chili-peppers)

I have the feeling that it happends when there are a lot of notes at the same time (chords)

**Comment by emersion** [comment]
Not Our Bug(tm)

![screenshot from 2017-12-13 02-54-44](https://user-images.githubusercontent.com/506932/33917907-117aadba-dfb1-11e7-9a96-2236351083a0.png)

Opening the MIDI file in a [sequencer](https://onlinesequencer.net) revealed that the original file has such patterns. I'm afraid we can't really do anything about it.
