### ISSUE TITLE
Segmentation Fault in Midi

### ISSUE THREAD

**Issue by FooB4r** [fanfaresimulator/fanfaresimulator#33]
Getting a segfault using this file -> [download](https://freemidi.org/download-2896-hotel-california-eagles)

Gdb:
![midisegfault](https://user-images.githubusercontent.com/18214834/33811239-a8947700-de10-11e7-8201-2d1d7c4f625e.png)

**Comment by emersion** [comment]
Sava l'instrument qui n'existe pas
