### ISSUE TITLE
Estimate ping between server and each client

### ISSUE THREAD

**Issue by emersion** [fanfaresimulator/fanfaresimulator#35]
Bots don't start on time.

cc @fanfaresimulator/network

**Comment by FooB4r** [comment]
Ping will only give the RTT. We are interested in knowing Server -> Client time to start at the same moment.
The main problemn would be to ensure that partitions don't shift in time one from another. This can probably happend when the client is lagging.

We can check for timestamp sent by the client and send him time corrections, that will set his partition time.

**Comment by emersion** [comment]
>Ping will only give the RTT. We are interested in knowing Server -> Client time to start at the same moment.

RTT/2 might be good enough. We could explore more complex solutions afterwards.

>The main problemn would be to ensure that partitions don't shift in time one from another. This can probably happend when the client is lagging.
>
>We can check for timestamp sent by the client and send him time corrections, that will set his partition time.

The client shouldn't desynchronize because of a lag, because all is computed according to the time when the partition started playing. If a client is lagging, it will have frame drops, but all frames will still be in sync with the server.
